export const LANG_FR_TRANS = {


    Projects: `Projets`,
    Refresh: `rafraichir`,
    Archive: `Archiver`,
    'New Project': `Nouveau projet`,
    incomplete: `incomplet`,
    complete: `complet`,
    tasks: `tâches`,
    'tasks completed': `tâches terminées`,
    'tasks to be done': `tâches à effectuer`,
    Edit: `Modifier`,
    edit: `modifier`,
    Delete: `Supprimer`,
    Name: `Nom`,
    Search: `Chercher`,
    Status: `Statut`,
    Save: `Enregistrer`,
    Active: `Actif`,
    Inactive: `Inactif`,
    project: `projet`,
    Uploads: `Téléchargements`,
    'add task here': `Ajouter une tâche`,
    'Drop it, baby!': `Tirer un fichier ici`,
    'Load more': `Charger plus`,
    Added: 'Ajouté le',
    Upload: `Ajouter un fichier`,
    Priority: `Urgent`,
    Indent: `Indenter`,
    "Sign in": `Connexion`,
    "Last updated": `Dernière modification le`,


};
