export const LANG_EN_TRANS = {


    Projects: `Projects`,
    Refresh: `Refresh`,
    tasks_completed: `tasks completed`,
    tasks_to_be_done: `tasks to be done`,
    complete: `complete`,
    Search: `Search`,
    Archive: `Archive`,
    'New Project': `New project`,
    incomplete: `incomplete`,
    tasks: `tasks`,
    Edit: `Edit`,
    edit: `edit`,
    Delete: `Delete`,
    Name: `Name`,
    Status: `Status`,
    Save: `Save`,
    Tasks: `tasks`,
    Slug: `Slug`,
    Month: `Month`,
    Client: `Client`,
    Clients: `Clients`,
    Comment: 'Comment',
    new_client: `New Client`,
    Export: `Export`,
    sign_out: `Sign out`,
    Channels: `Channels`,
    Active: `Active`,
    Inactive: `Inactive`,
    project: `project`,
    Uploads: `Uploads`,
    'add task here': `Add task here`,
    'Drop it, baby!': `Upload a file here`,
    'Load more': `Load more`,
    Added: 'Added on',
    Upload: `Upload a file`,
    Priority: `Priority`,
    "Assign to": `Assign to`,
    Indent: `Indent`,
    "Sign in": `Sign in`,
    "Last updated": `Last updated on`,

};
